server:
  port: 0

spring:
  application:
    name: sala-service
  datasource:
    username: adminLenin
    url: jdbc:sqlserver://azurelenin.database.windows.net:1433;database=pelicula;
    password: Ingreso1
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.value}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8671/eureka
